import { Metadata } from "next";
import PeanutButterSupplierNorthMacedonia from "./PeanutButterSupplierNorthMacedonia";
import MarketSchema from "@/components/MarketSchema";

export const metadata: Metadata = {
  title: "Peanut Butter Supplier North Macedonia | Indian Foodtech",
  description:
    "Reliable peanut butter supplier in North Macedonia. Indian Foodtech offers premium bulk supply, private label, and solutions for the Macedonian market.",
  keywords: [
    "peanut butter supplier north macedonia",
    "bulk peanut butter north macedonia",
    "private label peanut butter north macedonia",
    "peanut butter supplier skopje",
    "macedonian food importers",
    "balkan peanut butter supply",
    "peanut butter import North Macedonia",
    "North Macedonia peanut butter supplier",
    "peanut butter manufacturer North Macedonia",
    "private label peanut butter North Macedonia",
    "bulk peanut butter North Macedonia",
    "wholesale peanut butter North Macedonia",
    "import peanut butter North Macedonia",
    "peanut butter exporter North Macedonia",
    "natural peanut butter North Macedonia",
    "organic peanut butter North Macedonia",
    "creamy peanut butter North Macedonia",
    "crunchy peanut butter North Macedonia",
    "high protein peanut butter North Macedonia",
    "premium peanut butter North Macedonia",
    "peanut butter distributor North Macedonia",
    "AGRION peanut butter",
    "food importer North Macedonia",
    "food distributor North Macedonia",
    "private label food manufacturer North Macedonia",
    "путер од кикирики Македонија",
    "добавувач на путер од кикирики Македонија",
    "производител на путер од кикирики Македонија",
    "путер од кикирики на големо",
    "увоз на путер од кикирики",
    "извоз на путер од кикирики",
    "природен путер од кикирики",
    "органски путер од кикирики",
    "кремаст путер од кикирики",
    "крцкав путер од кикирики",
    "високопротеински путер од кикирики",
    "путер од кикирики приватна марка",
    "private label путер од кикирики",
    "договорно производство",
    "увозник на храна Македонија",
    "дистрибутер на храна Македонија",
    "добавувач на храна Македонија",
    "buy peanut butter in bulk North Macedonia",
    "wholesale peanut butter supplier North Macedonia",
    "private label peanut butter manufacturer North Macedonia",
    "natural peanut butter distributor North Macedonia",
    "organic peanut butter supplier North Macedonia",
    "high protein peanut butter North Macedonia",
    "peanut butter for supermarkets North Macedonia",
    "food importer North Macedonia",
    "bulk peanut butter exporter to North Macedonia",
    "premium peanut butter supplier North Macedonia",
    "путер од кикирики на големо Македонија",
    "добавувач на путер од кикирики за супермаркети",
    "производител на путер од кикирики приватна марка",
    "увозник на путер од кикирики Македонија",
    "дистрибутер на путер од кикирики Македонија",
    "органски путер од кикирики Македонија",
    "peanut butter supplier Skopje",
    "wholesale peanut butter North Macedonia",
    "private label peanut butter North Macedonia",
    "путер од кикирики Скопје",
    "добавувач на путер од кикирики Македонија",
    "путер од кикирики на големо Македонија",
    "увозник на путер од кикирики Скопје",
    "OEM peanut butter North Macedonia",
    "ODM peanut butter supplier North Macedonia",
    "private label nut butter manufacturer North Macedonia",
    "bulk peanut butter for retailers",
    "healthy food distributor North Macedonia",
    "OEM путер од кикирики",
    "ODM путер од кикирики",
    "производство на путер од кикирики приватна марка",
    "добавувач на здрава храна Македонија",
    "protein peanut butter North Macedonia",
    "organic peanut butter North Macedonia",
    "vegan peanut butter North Macedonia",
    "sugar free peanut butter North Macedonia",
    "natural peanut butter North Macedonia",
    "протеински путер од кикирики",
    "органски путер од кикирики",
    "вегански путер од кикирики",
    "путер од кикирики без шеќер",
    "природен путер од кикирики",
    "sports nutrition peanut butter North Macedonia",
    "fitness peanut butter North Macedonia",
    "healthy snack supplier North Macedonia",
    "gym nutrition peanut butter North Macedonia",
    "high protein spread North Macedonia",
    "спортска исхрана путер од кикирики",
    "фитнес путер од кикирики",
    "здрава ужина Македонија",
    "North Macedonia peanut butter market",
    "North Macedonia nut butter market",
  ],
  openGraph: {
    title: "Peanut Butter Supplier North Macedonia | Indian Foodtech",
    description:
      "High-quality peanut butter exported from India to North Macedonia. Premium bulk supply and customized private label solutions for Balkan distributors.",
    url: "https://www.indianfoodtech.com/peanut-butter-supplier-north-macedonia",
    siteName: "Indian Foodtech",
    type: "website",
    locale: "en_MK",
  },
  alternates: {
    canonical: "https://www.indianfoodtech.com/peanut-butter-supplier-north-macedonia",
    languages: {
      "en-MK": "https://www.indianfoodtech.com/peanut-butter-supplier-north-macedonia",
      "x-default": "https://www.indianfoodtech.com/",
    },
  },
};

export default function Page() {
  return (
    <>
      <MarketSchema
        country="North Macedonia"
        type="Supplier"
        description="Reliable peanut butter supplier in North Macedonia. Indian Foodtech offers premium bulk supply, private label, and solutions for the Macedonian market. Indian Foodtech offers premium bulk supply and private label solutions."
        url="https://www.indianfoodtech.com/peanut-butter-supplier-north-macedonia"
      />
      <PeanutButterSupplierNorthMacedonia />
    </>
  );
}
