import { Metadata } from "next";
import PeanutButterExportToFrance from "./PeanutButterExportToFrance";
import MarketSchema from "@/components/MarketSchema";

export const metadata: Metadata = {
  title: "Peanut Butter Exporter to France | Bulk Export from India",
  description:
    "Reliable peanut butter exporter to France. Indian Foodtech offers premium bulk supply, private label, and industrial solutions for the French market.",
  keywords: [
    "peanut butter exporter to france",
    "bulk peanut butter france",
    "private label peanut butter france",
    "exportateur vers beurre de cacahuète",
    "beurre de cacahuète en gros",
    "exportation vers de beurre de cacahuète france",
    "Peanut butter supplier paris",
    "french food exporters to",
    "european peanut butter supply",
    "peanut butter export to France",
    "France peanut butter supplier",
    "peanut butter manufacturer France",
    "private label peanut butter France",
    "bulk peanut butter France",
    "wholesale peanut butter France",
    "export peanut butter to France",
    "peanut butter exporter France",
    "natural peanut butter France",
    "organic peanut butter France",
    "creamy peanut butter France",
    "crunchy peanut butter France",
    "high protein peanut butter France",
    "premium peanut butter France",
    "peanut butter distributor France",
    "AGRION peanut butter",
    "food exporter to France",
    "food distributor France",
    "private label food manufacturer France",
    "beurre de cacahuète France",
    "fournisseur de beurre de cacahuète France",
    "fabricant de beurre de cacahuète France",
    "beurre de cacahuète en gros",
    "beurre de cacahuète en vrac",
    "exportation vers de beurre de cacahuète",
    "exportateur de beurre de cacahuète",
    "beurre de cacahuète naturel",
    "beurre de cacahuète biologique",
    "beurre de cacahuète crémeux",
    "beurre de cacahuète croquant",
    "beurre de cacahuète riche en protéines",
    "marque distributeur beurre de cacahuète",
    "fabrication sous marque privée",
    "distributeur alimentaire France",
    "fournisseur alimentaire France",
    "exportateur vers alimentaire France",
    "buy peanut butter in bulk France",
    "wholesale peanut butter supplier France",
    "private label peanut butter manufacturer France",
    "natural peanut butter distributor France",
    "organic peanut butter supplier France",
    "high protein peanut butter France",
    "peanut butter for supermarkets France",
    "food exporter to France",
    "bulk peanut butter exporter to France",
    "premium peanut butter supplier France",
    "acheter beurre de cacahuète en gros France",
    "fournisseur de beurre de cacahuète pour supermarchés",
    "fabricant de beurre de cacahuète marque privée",
    "exportateur vers de beurre de cacahuète France",
    "distributeur de beurre de cacahuète France",
    "beurre de cacahuète bio France",
    "peanut butter supplier Paris",
    "wholesale peanut butter France",
    "private label peanut butter France",
    "beurre de cacahuète Paris",
    "fournisseur de beurre de cacahuète France",
    "beurre de cacahuète en gros France",
    "exportateur vers de beurre de cacahuète Paris",
    "OEM peanut butter France",
    "ODM peanut butter supplier France",
    "private label peanut butter manufacturer France",
    "bulk peanut butter for retailers",
    "healthy food distributor France",
    "OEM beurre de cacahuète",
    "ODM beurre de cacahuète",
    "fabrication de beurre de cacahuète sous marque privée",
    "fournisseur de produits alimentaires sains France",
    "organic peanut butter France",
    "vegan peanut butter France",
    "clean label peanut butter France",
    "protein peanut butter France",
    "sugar free peanut butter France",
    "beurre de cacahuète bio",
    "beurre de cacahuète vegan",
    "beurre de cacahuète sans sucre",
    "beurre de cacahuète naturel",
    "beurre de cacahuète protéiné",
    "French private label food supplier",
    "bulk food imports France",
    "healthy food distribution Europe",
    "organic food supplier France",
    "vegan food supplier France",
    "no added sugar peanut butter France",
    "protein peanut butter France",
    "clean label peanut butter France",
    "peanut butter supplier for hotels France",
    "peanut butter for catering France",
    "healthy snack supplier France",
    "French food distributor bulk",
    "organic grocery supplier France",
    "vegan snack supplier France",
    "wholesale healthy food Europe",
    "premium peanut butter France",
    "healthy food exporter France",
    "French organic food exporter to"
  ],
  openGraph: {
    title: "Peanut Butter Exporter to France | Indian Foodtech",
    description:
      "High-quality peanut butter exported from India to France. Premium bulk supply and customized private label solutions for Western European distributors.",
    url: "https://www.indianfoodtech.com/peanut-butter-export-to-france",
    siteName: "Indian Foodtech",
    type: "website",
    locale: "en_FR",
  },
  alternates: {
    canonical: "https://www.indianfoodtech.com/peanut-butter-export-to-france",
    languages: {
      "en-FR": "https://www.indianfoodtech.com/peanut-butter-export-to-france",
      "x-default": "https://www.indianfoodtech.com/",
    },
  },
};

export default function PeanutButterExportToFrancePage() {
  return (
    <>
      <MarketSchema
        country="France"
        type="Exporter"
        description="Reliable peanut butter exporter to France. Indian Foodtech offers premium bulk supply, private label, and industrial solutions for the French market."
        url="https://www.indianfoodtech.com/peanut-butter-export-to-france"
      />
      <PeanutButterExportToFrance />
    </>
  );
}
