import { Metadata } from "next";
import PeanutButterSupplierNorway from "./PeanutButterSupplierNorway";
import MarketSchema from "@/components/MarketSchema";

export const metadata: Metadata = {
  title: "Peanut Butter Supplier Norway | Peanøttsmør-Leverandør",
  description:
    "Reliable peanut butter supplier in Norway. Indian Foodtech offers premium bulk supply, private label, and industrial solutions for the Norwegian market.",
  keywords: [
    "peanut butter supplier norway",
    "bulk peanut butter norway",
    "private label peanut butter norway",
    "peanøttsmør leverandør",
    "peanøttsmør engros",
    "import av peanøttsmør norge",
    "peanut butter supplier oslo",
    "norwegian food importers",
    "scandinavian peanut butter supply",
    "peanut butter import Norway",
    "Norway peanut butter supplier",
    "peanut butter manufacturer Norway",
    "private label peanut butter Norway",
    "bulk peanut butter Norway",
    "wholesale peanut butter Norway",
    "import peanut butter Norway",
    "peanut butter exporter Norway",
    "natural peanut butter Norway",
    "organic peanut butter Norway",
    "creamy peanut butter Norway",
    "crunchy peanut butter Norway",
    "high protein peanut butter Norway",
    "premium peanut butter Norway",
    "peanut butter distributor Norway",
    "AGRION peanut butter",
    "food importer Norway",
    "food distributor Norway",
    "private label food manufacturer Norway",
    "peanøttsmør Norge",
    "leverandør av peanøttsmør Norge",
    "produsent av peanøttsmør Norge",
    "peanøttsmør engros",
    "peanøttsmør i bulk",
    "import av peanøttsmør",
    "eksport av peanøttsmør",
    "naturlig peanøttsmør",
    "økologisk peanøttsmør",
    "kremet peanøttsmør",
    "sprøtt peanøttsmør",
    "proteinrikt peanøttsmør",
    "private label peanøttsmør",
    "egen merkevare peanøttsmør",
    "kontraktsproduksjon peanøttsmør",
    "matimportør Norge",
    "matdistributør Norge",
    "matleverandør Norge",
    "buy peanut butter in bulk Norway",
    "wholesale peanut butter supplier Norway",
    "private label peanut butter manufacturer Norway",
    "natural peanut butter distributor Norway",
    "organic peanut butter supplier Norway",
    "high protein peanut butter Norway",
    "peanut butter for supermarkets Norway",
    "food importer Norway",
    "bulk peanut butter exporter to Norway",
    "premium peanut butter supplier Norway",
    "peanøttsmør engros Norge",
    "leverandør av peanøttsmør til supermarkeder",
    "private label peanøttsmør produsent",
    "importør av peanøttsmør Norge",
    "distributør av peanøttsmør Norge",
    "økologisk peanøttsmør Norge",
    "peanut butter supplier Oslo",
    "wholesale peanut butter Norway",
    "private label peanut butter Norway",
    "peanøttsmør Oslo",
    "leverandør av peanøttsmør Norge",
    "peanøttsmør engros Norge",
    "importør av peanøttsmør Oslo",
    "OEM peanut butter Norway",
    "ODM peanut butter supplier Norway",
    "private label nut butter manufacturer Norway",
    "bulk peanut butter for retailers",
    "healthy food distributor Norway",
    "OEM peanøttsmør",
    "ODM peanøttsmør",
    "private label peanøttsmør produksjon",
    "leverandør av sunn mat Norge",
    "organic peanut butter Norway",
    "vegan peanut butter Norway",
    "protein peanut butter Norway",
    "sugar free peanut butter Norway",
    "natural peanut butter Norway",
    "økologisk peanøttsmør",
    "vegansk peanøttsmør",
    "proteinrikt peanøttsmør",
    "sukkerfritt peanøttsmør",
    "naturlig peanøttsmør",
    "sports nutrition peanut butter Norway",
    "fitness peanut butter Norway",
    "healthy snack supplier Norway",
    "gym nutrition peanut butter Norway",
    "high protein spread Norway",
    "sportsernæring peanøttsmør",
    "fitness peanøttsmør",
    "sunne snacks Norge",
    "proteinpålegg Norge",
    "private label peanøttsmør produsent Norge",
    "contract manufacturing peanut butter Norway",
    "white label peanut butter Norway",
    "OEM food manufacturer Norway",
    "custom peanut butter manufacturer Norway"
  ],
  openGraph: {
    title: "Peanut Butter Supplier Norway | Indian Foodtech",
    description:
      "High-quality peanut butter exported from India to Norway. Premium bulk supply and customized private label solutions for Scandinavian distributors.",
    url: "https://www.indianfoodtech.com/peanut-butter-supplier-norway",
    siteName: "Indian Foodtech",
    type: "website",
    locale: "en_NO",
  },
  alternates: {
    canonical: "https://www.indianfoodtech.com/peanut-butter-supplier-norway",
    languages: {
      "en-NO": "https://www.indianfoodtech.com/peanut-butter-supplier-norway",
      "x-default": "https://www.indianfoodtech.com/",
    },
  },
};

export default function Page() {
  return (
    <>
      <MarketSchema
        country="Norway"
        type="Supplier"
        description="Reliable peanut butter supplier in Norway. Indian Foodtech offers premium bulk supply and private label solutions for the Norwegian market."
        url="https://www.indianfoodtech.com/peanut-butter-supplier-norway"
      />
      <PeanutButterSupplierNorway />
    </>
  );
}
