import { Metadata } from "next";
import PeanutButterSupplierPoland from "./PeanutButterSupplierPoland";
import MarketSchema from "@/components/MarketSchema";

export const metadata: Metadata = {
  title: "Peanut Butter Supplier Poland | Dostawca Masla Orzechowego",
  description:
    "Reliable peanut butter supplier in Poland. Indian Foodtech offers premium bulk supply, private label, and industrial solutions for the Polish market.",
  keywords: [
    "peanut butter supplier poland",
    "bulk peanut butter poland",
    "private label peanut butter poland",
    "dostawca masla orzechowego",
    "hurtownia masla orzechowego",
    "import masla orzechowego polska",
    "peanut butter supplier warsaw",
    "polish food importers",
    "european peanut butter supply",
    "peanut butter import Poland",
    "Poland peanut butter supplier",
    "peanut butter manufacturer Poland",
    "private label peanut butter Poland",
    "bulk peanut butter Poland",
    "wholesale peanut butter Poland",
    "import peanut butter Poland",
    "peanut butter exporter Poland",
    "natural peanut butter Poland",
    "organic peanut butter Poland",
    "creamy peanut butter Poland",
    "crunchy peanut butter Poland",
    "high protein peanut butter Poland",
    "premium peanut butter Poland",
    "peanut butter distributor Poland",
    "AGRION peanut butter",
    "food importer Poland",
    "food distributor Poland",
    "private label food manufacturer Poland",
    "masło orzechowe Polska",
    "dostawca masła orzechowego Polska",
    "producent masła orzechowego Polska",
    "hurtownia masła orzechowego",
    "masło orzechowe hurt",
    "import masła orzechowego",
    "eksport masła orzechowego",
    "naturalne masło orzechowe",
    "ekologiczne masło orzechowe",
    "kremowe masło orzechowe",
    "chrupiące masło orzechowe",
    "wysokobiałkowe masło orzechowe",
    "masło orzechowe marki własnej",
    "private label masło orzechowe",
    "produkcja kontraktowa",
    "importer żywności Polska",
    "dystrybutor żywności Polska",
    "dostawca żywności Polska",
    "buy peanut butter in bulk Poland",
    "wholesale peanut butter supplier Poland",
    "private label peanut butter manufacturer Poland",
    "natural peanut butter distributor Poland",
    "organic peanut butter supplier Poland",
    "high protein peanut butter Poland",
    "peanut butter for supermarkets Poland",
    "food importer Poland",
    "bulk peanut butter exporter to Poland",
    "premium peanut butter supplier Poland",
    "hurtownia masła orzechowego Polska",
    "dostawca masła orzechowego do supermarketów",
    "producent masła orzechowego marki własnej",
    "importer masła orzechowego Polska",
    "dystrybutor masła orzechowego Polska",
    "ekologiczne masło orzechowe Polska",
    "peanut butter supplier Warsaw",
    "wholesale peanut butter Poland",
    "private label peanut butter Poland",
    "masło orzechowe Warszawa",
    "dostawca masła orzechowego Polska",
    "hurtownia masła orzechowego Polska",
    "importer masła orzechowego Warszawa",
    "OEM peanut butter Poland",
    "ODM peanut butter supplier Poland",
    "private label nut butter manufacturer Poland",
    "bulk peanut butter for retailers",
    "healthy food distributor Poland",
    "OEM masło orzechowe",
    "ODM masło orzechowe",
    "produkcja masła orzechowego marki własnej",
    "dostawca zdrowej żywności Polska",
    "organic peanut butter Poland",
    "vegan peanut butter Poland",
    "protein peanut butter Poland",
    "sugar free peanut butter Poland",
    "natural peanut butter Poland",
    "ekologiczne masło orzechowe",
    "wegańskie masło orzechowe",
    "wysokobiałkowe masło orzechowe",
    "masło orzechowe bez cukru",
    "naturalne masło orzechowe",
    "sports nutrition peanut butter Poland",
    "fitness peanut butter Poland",
    "healthy snack supplier Poland",
    "gym nutrition peanut butter Poland",
    "high protein spread Poland",
    "odżywki sportowe masło orzechowe",
    "fitness masło orzechowe",
    "zdrowe przekąski Polska",
    "wysokobiałkowe smarowidło",
    "private label peanut butter manufacturer Poland",
    "contract manufacturing peanut butter Poland",
    "white label peanut butter Poland",
    "OEM food manufacturer Poland",
    "custom peanut butter manufacturer Poland",
    "Poland peanut butter market",
    "Poland nut butter market",
  ],
  openGraph: {
    title: "Peanut Butter Supplier Poland | Indian Foodtech",
    description:
      "High-quality peanut butter exported from India to Poland. Premium bulk supply and customized private label solutions for Polish distributors.",
    url: "https://www.indianfoodtech.com/peanut-butter-supplier-poland",
    siteName: "Indian Foodtech",
    type: "website",
    locale: "en_PL",
  },
  alternates: {
    canonical: "https://www.indianfoodtech.com/peanut-butter-supplier-poland",
    languages: {
      "en-PL": "https://www.indianfoodtech.com/peanut-butter-supplier-poland",
      "x-default": "https://www.indianfoodtech.com/",
    },
  },
};

export default function Page() {
  return (
    <>
      <MarketSchema
        country="Poland"
        type="Supplier"
        description="Reliable peanut butter supplier in Poland. Indian Foodtech offers premium bulk supply and private label solutions for the Polish market."
        url="https://www.indianfoodtech.com/peanut-butter-supplier-poland"
      />
      <PeanutButterSupplierPoland />
    </>
  );
}
