import { Metadata } from "next";
import PeanutButterSupplierNetherlands from "./PeanutButterSupplierNetherlands";
import MarketSchema from "@/components/MarketSchema";

export const metadata: Metadata = {
  title: "Peanut Butter Supplier Netherlands | Pindakaas Leverancier",
  description:
    "Reliable peanut butter supplier in the Netherlands. Indian Foodtech offers premium bulk supply, private label, and industrial solutions for the Dutch market.",
  keywords: [
    "peanut butter supplier netherlands",
    "bulk peanut butter netherlands",
    "private label peanut butter netherlands",
    "pindakaas leverancier",
    "pindakaas groothandel",
    "import van pindakaas nederland",
    "peanut butter supplier amsterdam",
    "dutch food importers",
    "european peanut butter supply",
    "peanut butter import Netherlands",
    "Netherlands peanut butter supplier",
    "peanut butter manufacturer Netherlands",
    "private label peanut butter Netherlands",
    "bulk peanut butter Netherlands",
    "wholesale peanut butter Netherlands",
    "import peanut butter Netherlands",
    "peanut butter exporter Netherlands",
    "natural peanut butter Netherlands",
    "organic peanut butter Netherlands",
    "creamy peanut butter Netherlands",
    "crunchy peanut butter Netherlands",
    "high protein peanut butter Netherlands",
    "premium peanut butter Netherlands",
    "peanut butter distributor Netherlands",
    "AGRION peanut butter",
    "food importer Netherlands",
    "food distributor Netherlands",
    "private label food manufacturer Netherlands",
    "pindakaas Nederland",
    "pindakaas leverancier Nederland",
    "pindakaas fabrikant Nederland",
    "pindakaas groothandel",
    "pindakaas in bulk",
    "pindakaas import",
    "pindakaas export",
    "natuurlijke pindakaas",
    "biologische pindakaas",
    "romige pindakaas",
    "crunchy pindakaas",
    "eiwitrijke pindakaas",
    "private label pindakaas",
    "huismerk pindakaas",
    "contractproductie pindakaas",
    "voedselimporteur Nederland",
    "voedseldistributeur Nederland",
    "voedingsleverancier Nederland",
    "buy peanut butter in bulk Netherlands",
    "wholesale peanut butter supplier Netherlands",
    "private label peanut butter manufacturer Netherlands",
    "natural peanut butter distributor Netherlands",
    "organic peanut butter supplier Netherlands",
    "high protein peanut butter Netherlands",
    "peanut butter for supermarkets Netherlands",
    "food importer Netherlands",
    "bulk peanut butter exporter to Netherlands",
    "premium peanut butter supplier Netherlands",
    "pindakaas groothandel Nederland",
    "pindakaas leverancier voor supermarkten",
    "private label pindakaas fabrikant",
    "pindakaas importeur Nederland",
    "biologische pindakaas leverancier",
    "eiwitrijke pindakaas Nederland",
    "peanut butter supplier Amsterdam",
    "wholesale peanut butter Netherlands",
    "private label peanut butter Netherlands",
    "pindakaas Amsterdam",
    "pindakaas leverancier Nederland",
    "pindakaas groothandel Nederland",
    "pindakaas importeur Rotterdam",
    "OEM peanut butter Netherlands",
    "ODM peanut butter supplier Netherlands",
    "private label nut butter manufacturer Netherlands",
    "bulk peanut butter for retailers",
    "healthy food distributor Netherlands",
    "OEM pindakaas",
    "ODM pindakaas",
    "private label pindakaas productie",
    "huismerk pindakaas fabrikant",
    "gezonde voeding leverancier Nederland",
    "organic peanut butter Netherlands",
    "vegan peanut butter Netherlands",
    "protein peanut butter Netherlands",
    "sugar free peanut butter Netherlands",
    "natural peanut butter Netherlands",
    "biologische pindakaas",
    "vegan pindakaas",
    "eiwitrijke pindakaas",
    "suikervrije pindakaas",
    "natuurlijke pindakaas",
    "sports nutrition peanut butter Netherlands",
    "fitness peanut butter Netherlands",
    "healthy snack supplier Netherlands",
    "gym nutrition peanut butter Netherlands",
    "high protein spread Netherlands",
    "sportvoeding pindakaas",
    "fitness pindakaas",
    "gezonde snacks Nederland",
    "eiwitrijke spreads Nederland",
    "private label pindakaas fabrikant Nederland",
    "contract manufacturing peanut butter Netherlands",
    "white label peanut butter Netherlands",
    "OEM food manufacturer Netherlands",
    "custom peanut butter manufacturer Netherlands"
  ],
  openGraph: {
    title: "Peanut Butter Supplier Netherlands | Indian Foodtech",
    description:
      "High-quality peanut butter exported from India to the Netherlands. Premium bulk supply and customized private label solutions for Dutch distributors.",
    url: "https://www.indianfoodtech.com/peanut-butter-supplier-netherlands",
    siteName: "Indian Foodtech",
    type: "website",
    locale: "en_NL",
  },
  alternates: {
    canonical: "https://www.indianfoodtech.com/peanut-butter-supplier-netherlands",
    languages: {
      "en-NL": "https://www.indianfoodtech.com/peanut-butter-supplier-netherlands",
      "x-default": "https://www.indianfoodtech.com/",
    },
  },
};

export default function Page() {
  return (
    <>
      <MarketSchema
        country="Netherlands"
        type="Supplier"
        description="Reliable peanut butter supplier in the Netherlands. Indian Foodtech offers premium bulk supply and private label solutions for the Dutch market."
        url="https://www.indianfoodtech.com/peanut-butter-supplier-netherlands"
      />
      <PeanutButterSupplierNetherlands />
    </>
  );
}
