import { Metadata } from "next";
import PeanutButterSupplierMoldova from "./PeanutButterSupplierMoldova";
import MarketSchema from "@/components/MarketSchema";

export const metadata: Metadata = {
  title: "Peanut Butter Supplier Moldova | Furnizor de Unt de Arahide",
  description:
    "Reliable peanut butter supplier in Moldova. Indian Foodtech offers premium bulk supply, private label, and industrial solutions for the Moldovan market.",
  keywords: [
    "peanut butter supplier moldova",
    "bulk peanut butter moldova",
    "private label peanut butter moldova",
    "furnizor unt de arahide",
    "unt de arahide en gros",
    "import unt de arahide moldova",
    "peanut butter supplier chisinau",
    "moldovan food importers",
    "eastern european peanut butter supply",
    "Peanut butter import Moldova",
    "Moldova peanut butter supplier",
    "peanut butter manufacturer Moldova",
    "private label peanut butter Moldova",
    "bulk peanut butter Moldova",
    "wholesale peanut butter Moldova",
    "import peanut butter Moldova",
    "peanut butter exporter Moldova",
    "natural peanut butter Moldova",
    "organic peanut butter Moldova",
    "creamy peanut butter Moldova",
    "crunchy peanut butter Moldova",
    "high protein peanut butter Moldova",
    "premium peanut butter Moldova",
    "peanut butter distributor Moldova",
    "AGRION peanut butter",
    "food importer Moldova",
    "food distributor Moldova",
    "private label food manufacturer Moldova",
    "unt de arahide Moldova",
    "furnizor unt de arahide Moldova",
    "producător unt de arahide Moldova",
    "unt de arahide en-gros",
    "unt de arahide vrac",
    "import unt de arahide",
    "export unt de arahide",
    "unt de arahide natural",
    "unt de arahide organic",
    "unt de arahide cremos",
    "unt de arahide crocant",
    "unt de arahide bogat în proteine",
    "unt de arahide marcă privată",
    "private label unt de arahide",
    "producție la comandă unt de arahide",
    "importator produse alimentare Moldova",
    "distribuitor produse alimentare Moldova",
    "furnizor produse alimentare Moldova",
    "buy peanut butter in bulk Moldova",
    "wholesale peanut butter supplier Moldova",
    "private label peanut butter manufacturer Moldova",
    "natural peanut butter distributor Moldova",
    "organic peanut butter supplier Moldova",
    "high protein peanut butter Moldova",
    "peanut butter for supermarkets Moldova",
    "food importer Moldova",
    "bulk peanut butter exporter to Moldova",
    "premium peanut butter supplier Moldova",
    "unt de arahide en-gros Moldova",
    "furnizor unt de arahide pentru supermarketuri",
    "producător unt de arahide marcă privată",
    "importator unt de arahide Moldova",
    "distribuitor unt de arahide Moldova",
    "unt de arahide organic Moldova",
    "peanut butter supplier Chisinau",
    "wholesale peanut butter Moldova",
    "private label peanut butter Moldova",
    "unt de arahide Chișinău",
    "furnizor unt de arahide Moldova",
    "unt de arahide en-gros Moldova",
    "importator unt de arahide Chișinău",
    "OEM peanut butter Moldova",
    "ODM peanut butter supplier Moldova",
    "private label nut butter manufacturer Moldova",
    "bulk peanut butter for retailers",
    "healthy food distributor Moldova",
    "OEM unt de arahide",
    "ODM unt de arahide",
    "unt de arahide marcă privată",
    "furnizor alimente sănătoase Moldova",
    "protein peanut butter Moldova",
    "organic peanut butter Moldova",
    "vegan peanut butter Moldova",
    "sugar free peanut butter Moldova",
    "natural peanut butter Moldova",
    "unt de arahide proteic",
    "unt de arahide organic",
    "unt de arahide vegan",
    "unt de arahide fără zahăr",
    "unt de arahide natural",
    "sports nutrition peanut butter Moldova",
    "fitness peanut butter Moldova",
    "healthy snack supplier Moldova",
    "gym nutrition peanut butter Moldova",
    "high protein spread Moldova",
    "nutriție sportivă unt de arahide",
    "unt de arahide pentru fitness",
    "gustări sănătoase Moldova",
  ],
  openGraph: {
    title: "Peanut Butter Supplier Moldova | Indian Foodtech",
    description:
      "High-quality peanut butter exported from India to Moldova. Premium bulk supply and customized private label solutions for Moldovan distributors.",
    url: "https://www.indianfoodtech.com/peanut-butter-supplier-moldova",
    siteName: "Indian Foodtech",
    type: "website",
    locale: "en_MD",
  },
  alternates: {
    canonical: "https://www.indianfoodtech.com/peanut-butter-supplier-moldova",
    languages: {
      "en-MD": "https://www.indianfoodtech.com/peanut-butter-supplier-moldova",
      "x-default": "https://www.indianfoodtech.com/",
    },
  },
};

export default function Page() {
  return (
    <>
      <MarketSchema
        country="Moldova"
        type="Supplier"
        description="Reliable peanut butter supplier in Moldova. Indian Foodtech offers premium bulk supply, private label, and industrial solutions for the Moldovan market."
        url="https://www.indianfoodtech.com/peanut-butter-supplier-moldova"
      />
      <PeanutButterSupplierMoldova />
    </>
  );
}
