import { Metadata } from "next";
import PeanutButterSupplierRomania from "./PeanutButterSupplierRomania";
import MarketSchema from "@/components/MarketSchema";

export const metadata: Metadata = {
  title: "Peanut Butter Supplier Romania | Furnizor de Unt de Arahide",
  description:
    "Reliable peanut butter supplier in Romania. Indian Foodtech offers premium bulk supply, private label, and industrial solutions for the Romanian market.",
  keywords: [
    "peanut butter supplier romania",
    "bulk peanut butter romania",
    "private label peanut butter romania",
    "furnizor de unt de arahide",
    "unt de arahide en-gros",
    "import de unt de arahide romania",
    "peanut butter supplier bucharest",
    "romanian food importers",
    "european peanut butter supply",
    "peanut butter import Romania",
    "Romania peanut butter supplier",
    "peanut butter manufacturer Romania",
    "private label peanut butter Romania",
    "bulk peanut butter Romania",
    "wholesale peanut butter Romania",
    "import peanut butter Romania",
    "peanut butter exporter Romania",
    "natural peanut butter Romania",
    "organic peanut butter Romania",
    "creamy peanut butter Romania",
    "crunchy peanut butter Romania",
    "high protein peanut butter Romania",
    "premium peanut butter Romania",
    "peanut butter distributor Romania",
    "AGRION peanut butter",
    "food importer Romania",
    "food distributor Romania",
    "private label food manufacturer Romania",
    "unt de arahide România",
    "furnizor unt de arahide România",
    "producător unt de arahide România",
    "unt de arahide en-gros",
    "unt de arahide vrac",
    "import unt de arahide",
    "export unt de arahide",
    "unt de arahide natural",
    "unt de arahide organic",
    "unt de arahide cremos",
    "unt de arahide crocant",
    "unt de arahide bogat în proteine",
    "unt de arahide marcă privată",
    "private label unt de arahide",
    "producție la comandă unt de arahide",
    "importator produse alimentare România",
    "distribuitor produse alimentare România",
    "furnizor produse alimentare România",
    "buy peanut butter in bulk Romania",
    "wholesale peanut butter supplier Romania",
    "private label peanut butter manufacturer Romania",
    "natural peanut butter distributor Romania",
    "organic peanut butter supplier Romania",
    "high protein peanut butter Romania",
    "peanut butter for supermarkets Romania",
    "food importer Romania",
    "bulk peanut butter exporter to Romania",
    "premium peanut butter supplier Romania",
    "unt de arahide en-gros România",
    "furnizor unt de arahide pentru supermarketuri",
    "producător unt de arahide marcă privată",
    "importator unt de arahide România",
    "distribuitor unt de arahide România",
    "unt de arahide organic România",
    "Peanut butter supplier Bucharest",
    "wholesale peanut butter Romania",
    "private label peanut butter Romania",
    "unt de arahide București",
    "furnizor unt de arahide România",
    "unt de arahide en-gros România",
    "importator unt de arahide București",
    "OEM peanut butter Romania",
    "ODM peanut butter supplier Romania",
    "private label nut butter manufacturer Romania",
    "bulk peanut butter for retailers",
    "healthy food distributor Romania",
    "OEM unt de arahide",
    "ODM unt de arahide",
    "unt de arahide marcă privată",
    "furnizor alimente sănătoase România",
    "organic peanut butter Romania",
    "vegan peanut butter Romania",
    "protein peanut butter Romania",
    "sugar free peanut butter Romania",
    "natural peanut butter Romania",
    "unt de arahide organic",
    "unt de arahide vegan",
    "unt de arahide proteic",
    "unt de arahide fără zahăr",
    "unt de arahide natural",
    "sports nutrition peanut butter Romania",
    "fitness peanut butter Romania",
    "healthy snack supplier Romania",
    "gym nutrition peanut butter Romania",
    "high protein spread Romania",
    "nutriție sportivă unt de arahide",
    "unt de arahide fitness",
    "gustări sănătoase România",
    "cremă proteică de arahide",
    "private label peanut butter manufacturer Romania",
    "contract manufacturing peanut butter Romania",
    "white label peanut butter Romania",
    "OEM food manufacturer Romania",
    "custom peanut butter manufacturer Romania"
  ],
  openGraph: {
    title: "Peanut Butter Supplier Romania | Indian Foodtech",
    description:
      "High-quality peanut butter exported from India to Romania. Premium bulk supply and customized private label solutions for Romanian distributors.",
    url: "https://www.indianfoodtech.com/peanut-butter-supplier-romania",
    siteName: "Indian Foodtech",
    type: "website",
    locale: "en_RO",
  },
  alternates: {
    canonical: "https://www.indianfoodtech.com/peanut-butter-supplier-romania",
    languages: {
      "en-RO": "https://www.indianfoodtech.com/peanut-butter-supplier-romania",
      "x-default": "https://www.indianfoodtech.com/",
    },
  },
};

export default function Page() {
  return (
    <>
      <MarketSchema
        country="Romania"
        type="Supplier"
        description="Reliable peanut butter supplier in Romania. Indian Foodtech offers premium bulk supply and private label solutions for the Romanian market."
        url="https://www.indianfoodtech.com/peanut-butter-supplier-romania"
      />
      <PeanutButterSupplierRomania />
    </>
  );
}
