import { Metadata } from "next";
import MarketSchema from "@/components/MarketSchema";
import PeanutButterImportUnitedStates from "./PeanutButterImportUnitedStates";

export const metadata: Metadata = {
  title: "Peanut Butter Importer United States | Indian Foodtech",
  description:
    "Reliable peanut butter importer in United States. Indian Foodtech offers premium bulk supply, private label, and industrial solutions for the American market.",
  keywords: [
    "peanut butter importer united states",
    "bulk peanut butter usa",
    "private label peanut butter america",
    "peanut butter supplier new york",
    "us food importers",
    "bulk nut butter supply",
    "peanut butter import USA",
    "peanut butter import United States",
    "USA peanut butter supplier",
    "United States peanut butter supplier",
    "peanut butter manufacturer USA",
    "private label peanut butter USA",
    "bulk peanut butter USA",
    "wholesale peanut butter USA",
    "import peanut butter USA",
    "peanut butter exporter USA",
    "natural peanut butter USA",
    "organic peanut butter USA",
    "creamy peanut butter USA",
    "crunchy peanut butter USA",
    "high protein peanut butter USA",
    "premium peanut butter USA",
    "peanut butter distributor USA",
    "AGRION peanut butter",
    "food importer USA",
    "food distributor USA",
    "private label food manufacturer USA",
    "peanut butter wholesaler USA",
    "bulk peanut butter supplier USA",
    "healthy peanut butter USA",
    "vegan peanut butter USA",
    "sugar free peanut butter USA",
    "protein peanut butter USA",
    "food service peanut butter USA",
    "nut butter supplier USA",
    "buy peanut butter in bulk USA",
    "wholesale peanut butter supplier USA",
    "private label peanut butter manufacturer USA",
    "natural peanut butter distributor USA",
    "organic peanut butter supplier USA",
    "high protein peanut butter USA",
    "peanut butter for supermarkets USA",
    "food importer USA",
    "bulk peanut butter exporter to USA",
    "premium peanut butter supplier USA",
    "private label peanut butter USA",
    "OEM peanut butter USA",
    "ODM peanut butter manufacturer USA",
    "food service peanut butter supplier USA",
    "healthy food distributor USA",
    "peanut butter supplier New York",
    "peanut butter supplier Los Angeles",
    "wholesale peanut butter USA",
    "private label peanut butter USA",
    "organic peanut butter USA",
    "bulk peanut butter Texas",
    "food importer California",
    "OEM peanut butter USA",
    "ODM peanut butter supplier USA",
    "private label nut butter manufacturer USA",
    "bulk peanut butter for retailers",
    "healthy food distributor USA",
    "supermarket peanut butter supplier USA",
    "natural peanut butter distributor USA",
    "organic peanut butter supplier USA",
    "high protein peanut butter USA",
    "peanut butter for supermarkets USA",
    "food importer USA",
    "bulk peanut butter exporter to USA",
    "premium peanut butter supplier USA",
    "private label peanut butter USA",
    "OEM peanut butter USA",
    "ODM peanut butter manufacturer USA",
    "food service peanut butter supplier USA",
    "healthy food distributor USA",
    "peanut butter supplier New York",
    "peanut butter supplier Los Angeles",
    "wholesale peanut butter USA",
    "private label peanut butter USA",
    "organic peanut butter USA",
    "bulk peanut butter Texas",
    "food importer California",
    "OEM peanut butter USA",
    "ODM peanut butter supplier USA",
    "private label nut butter manufacturer USA",
    "bulk peanut butter for retailers",
    "healthy food distributor USA",
    "supermarket peanut butter supplier USA",
    "organic peanut butter USA",
    "natural peanut butter USA",
    "vegan peanut butter USA",
    "protein peanut butter USA",
    "sugar free peanut butter USA",
    "clean label peanut butter USA",
    "non GMO peanut butter USA",
    "gluten free peanut butter USA",
    "healthy peanut butter USA",
    "Amazon peanut butter supplier USA",
    "Costco peanut butter supplier",
    "Walmart peanut butter supplier",
    "food service peanut butter USA",
    "restaurant supply peanut butter USA",
    "HORECA peanut butter supplier USA",
    "bulk peanut butter for bakeries",
    "bulk peanut butter for food manufacturers",
    "private label peanut butter manufacturer USA",
    "white label peanut butter USA",
    "contract manufacturing peanut butter USA",
    "OEM food manufacturer USA",
    "nut butter private label supplier USA",
    "custom peanut butter manufacturer USA",
    "protein peanut butter wholesale USA",
    "gym nutrition peanut butter USA",
    "fitness peanut butter supplier USA",
    "sports nutrition peanut butter USA",
    "healthy snack supplier USA",
    "high protein spreads USA"
  ],
  openGraph: {
    title: "Peanut Butter Importer United States | Indian Foodtech",
    description:
      "High-quality peanut butter exported from India to United States. Premium bulk supply and customized private label solutions for North American distributors.",
    url: "https://www.indianfoodtech.com/peanut-butter-import-united-states",
    siteName: "Indian Foodtech",
    type: "website",
    locale: "en_US",
  },
  alternates: {
    canonical:
      "https://www.indianfoodtech.com/peanut-butter-import-united-states",
    languages: {
      "en-US": "https://www.indianfoodtech.com/peanut-butter-import-united-states",
      "x-default": "https://www.indianfoodtech.com/",
    },
  },
};

export default function Page() {
  return (
    <>
      <MarketSchema
        country="United States"
        type="Importer"
        description="Reliable peanut butter importer in United States. Indian Foodtech offers premium bulk supply, private label, and industrial solutions for the American market."
        url="https://www.indianfoodtech.com/peanut-butter-import-united-states"
      />
      <PeanutButterImportUnitedStates />
    </>
  );
}
