import { Metadata } from "next";
import PeanutButterSupplierSerbia from "./PeanutButterSupplierSerbia";
import MarketSchema from "@/components/MarketSchema";

export const metadata: Metadata = {
  title: "Peanut Butter Supplier Serbia | Bulk peanut butter Export from India",
  description:
    "Reliable peanut butter supplier in Serbia. Indian Foodtech offers premium bulk supply, private label, and industrial solutions for the Serbian market.",
  keywords: [
    "peanut butter supplier serbia",
    "bulk peanut butter serbia",
    "private label peanut butter serbia",
    "peanut butter supplier belgrade",
    "serbian food importers",
    "balkan peanut butter supply",
    "peanut butter import Serbia",
    "Serbia peanut butter supplier",
    "peanut butter manufacturer Serbia",
    "private label peanut butter Serbia",
    "bulk peanut butter Serbia",
    "wholesale peanut butter Serbia",
    "import peanut butter Serbia",
    "peanut butter exporter Serbia",
    "natural peanut butter Serbia",
    "organic peanut butter Serbia",
    "creamy peanut butter Serbia",
    "crunchy peanut butter Serbia",
    "high protein peanut butter Serbia",
    "premium peanut butter Serbia",
    "peanut butter distributor Serbia",
    "AGRION peanut butter",
    "food importer Serbia",
    "food distributor Serbia",
    "private label food manufacturer Serbia",
    "kikiriki puter Srbija",
    "dobavljač kikiriki putera Srbija",
    "proizvođač kikiriki putera Srbija",
    "veleprodaja kikiriki putera",
    "kikiriki puter na veliko",
    "uvoz kikiriki putera",
    "izvoz kikiriki putera",
    "prirodni kikiriki puter",
    "organski kikiriki puter",
    "kremasti kikiriki puter",
    "hrskavi kikiriki puter",
    "proteinski kikiriki puter",
    "kikiriki puter privatne robne marke",
    "private label kikiriki puter",
    "ugovorna proizvodnja",
    "uvoznik hrane Srbija",
    "distributer hrane Srbija",
    "dobavljač hrane Srbija",
    "buy peanut butter in bulk Serbia",
    "wholesale peanut butter supplier Serbia",
    "private label peanut butter manufacturer Serbia",
    "natural peanut butter distributor Serbia",
    "organic peanut butter supplier Serbia",
    "high protein peanut butter Serbia",
    "peanut butter for supermarkets Serbia",
    "food importer Serbia",
    "bulk peanut butter exporter to Serbia",
    "premium peanut butter supplier Serbia",
    "veleprodaja kikiriki putera Srbija",
    "dobavljač kikiriki putera za supermarkete",
    "proizvođač kikiriki putera privatne robne marke",
    "uvoznik kikiriki putera Srbija",
    "distributer kikiriki putera Srbija",
    "organski kikiriki puter Srbija",
    "Peanut butter supplier Belgrade",
    "wholesale peanut butter Serbia",
    "private label peanut butter Serbia",
    "kikiriki puter Beograd",
    "dobavljač kikiriki putera Srbija",
    "veleprodaja kikiriki putera Srbija",
    "uvoznik kikiriki putera Beograd",
    "OEM peanut butter Serbia",
    "ODM peanut butter supplier Serbia",
    "private label nut butter manufacturer Serbia",
    "bulk peanut butter for retailers",
    "healthy food distributor Serbia",
    "OEM kikiriki puter",
    "ODM kikiriki puter",
    "proizvodnja kikiriki putera privatne robne marke",
    "dobavljač zdrave hrane Srbija",
    "protein peanut butter Serbia",
    "organic peanut butter Serbia",
    "vegan peanut butter Serbia",
    "sugar free peanut butter Serbia",
    "natural peanut butter Serbia",
    "proteinski kikiriki puter",
    "organski kikiriki puter",
    "veganski kikiriki puter",
    "kikiriki puter bez šećera",
    "prirodni kikiriki puter",
    "sports nutrition peanut butter Serbia",
    "fitness peanut butter Serbia",
    "healthy snack supplier Serbia",
    "gym nutrition peanut butter Serbia",
    "high protein spread Serbia",
    "sportska ishrana kikiriki puter",
    "fitnes kikiriki puter",
    "zdrave grickalice Srbija",
    "proteinski namaz od kikirikija",
    "private label peanut butter manufacturer Serbia",
    "contract manufacturing peanut butter Serbia",
    "white label peanut butter Serbia",
    "OEM food manufacturer Serbia",
    "custom peanut butter manufacturer Serbia"
  ],
  openGraph: {
    title: "Peanut Butter Supplier Serbia | Indian Foodtech",
    description:
      "High-quality peanut butter exported from India to Serbia. Premium bulk supply and customized private label solutions for Serbian distributors.",
    url: "https://www.indianfoodtech.com/peanut-butter-supplier-serbia",
    siteName: "Indian Foodtech",
    type: "website",
    locale: "en_RS",
  },
  alternates: {
    canonical: "https://www.indianfoodtech.com/peanut-butter-supplier-serbia",
    languages: {
      "en-RS": "https://www.indianfoodtech.com/peanut-butter-supplier-serbia",
      "x-default": "https://www.indianfoodtech.com/",
    },
  },
};

export default function Page() {
  return (
    <>
      <MarketSchema
        country="Serbia"
        type="Supplier"
        description="Reliable peanut butter supplier in Serbia. Indian Foodtech offers premium bulk supply and private label solutions for the Serbian market."
        url="https://www.indianfoodtech.com/peanut-butter-supplier-serbia"
      />
      <PeanutButterSupplierSerbia />
    </>
  );
}
