import { Metadata } from "next";
import PeanutButterSupplierRussia from "./PeanutButterSupplierRussia";
import MarketSchema from "@/components/MarketSchema";

export const metadata: Metadata = {
  title: "Peanut Butter Supplier Russia | Indian Foodtech",
  description:
    "Reliable peanut butter supplier in Russia. Indian Foodtech offers premium bulk supply, private label, and industrial solutions for the Russian market.",
  keywords: [
    "peanut butter supplier russia",
    "bulk peanut butter russia",
    "private label peanut butter russia",
    "peanut butter supplier moscow",
    "russian food importers",
    "eurasian peanut butter supply",
    "peanut butter import Russia",
    "Russia peanut butter supplier",
    "peanut butter manufacturer Russia",
    "private label peanut butter Russia",
    "bulk peanut butter Russia",
    "wholesale peanut butter Russia",
    "import peanut butter Russia",
    "peanut butter exporter Russia",
    "natural peanut butter Russia",
    "organic peanut butter Russia",
    "creamy peanut butter Russia",
    "crunchy peanut butter Russia",
    "high protein peanut butter Russia",
    "premium peanut butter Russia",
    "peanut butter distributor Russia",
    "AGRION peanut butter",
    "food importer Russia",
    "food distributor Russia",
    "private label food manufacturer Russia",
    "арахисовая паста Россия",
    "поставщик арахисовой пасты Россия",
    "производитель арахисовой пасты Россия",
    "арахисовая паста оптом",
    "арахисовая паста крупным оптом",
    "импорт арахисовой пасты",
    "экспорт арахисовой пасты",
    "натуральная арахисовая паста",
    "органическая арахисовая паста",
    "кремовая арахисовая паста",
    "хрустящая арахисовая паста",
    "арахисовая паста с высоким содержанием белка",
    "арахисовая паста под собственной торговой маркой",
    "private label арахисовая паста",
    "контрактное производство арахисовой пасты",
    "импортер продуктов питания Россия",
    "дистрибьютор продуктов питания Россия",
    "поставщик продуктов питания Россия",
    "buy peanut butter in bulk Russia",
    "wholesale peanut butter supplier Russia",
    "private label peanut butter manufacturer Russia",
    "natural peanut butter distributor Russia",
    "organic peanut butter supplier Russia",
    "high protein peanut butter Russia",
    "peanut butter for supermarkets Russia",
    "food importer Russia",
    "bulk peanut butter exporter to Russia",
    "premium peanut butter supplier Russia",
    "арахисовая паста оптом Россия",
    "поставщик арахисовой пасты для супермаркетов",
    "производитель арахисовой пасты под собственной торговой маркой",
    "импортер арахисовой пасты Россия",
    "дистрибьютор арахисовой пасты Россия",
    "органическая арахисовая паста Россия",
    "peanut butter supplier Moscow",
    "wholesale peanut butter Russia",
    "private label peanut butter Russia",
    "арахисовая паста Москва",
    "поставщик арахисовой пасты Россия",
    "арахисовая паста оптом Россия",
    "импортер арахисовой пасты Москва",
    "OEM peanut butter Russia",
    "ODM peanut butter supplier Russia",
    "private label nut butter manufacturer Russia",
    "bulk peanut butter for retailers",
    "healthy food distributor Russia",
    "OEM арахисовая паста",
    "ODM арахисовая паста",
    "арахисовая паста под собственной торговой маркой",
    "поставщик здорового питания Россия",
    "protein peanut butter Russia",
    "organic peanut butter Russia",
    "vegan peanut butter Russia",
    "sugar free peanut butter Russia",
    "natural peanut butter Russia",
    "протеиновая арахисовая паста",
    "органическая арахисовая паста",
    "веганская арахисовая паста",
    "арахисовая паста без сахара",
    "натуральная арахисовая паста",
    "sports nutrition peanut butter Russia",
    "fitness peanut butter Russia",
    "healthy snack supplier Russia",
    "gym nutrition peanut butter Russia",
    "high protein spread Russia",
    "спортивное питание арахисовая паста",
    "арахисовая паста для фитнеса",
    "здоровые снеки Россия",
    "высокобелковая арахисовая паста",
    "private label peanut butter manufacturer Russia",
    "contract manufacturing peanut butter Russia",
    "white label peanut butter Russia",
    "OEM food manufacturer Russia",
    "custom peanut butter manufacturer Russia"
  ],
  openGraph: {
    title: "Peanut Butter Supplier Russia | Indian Foodtech",
    description:
      "High-quality peanut butter exported from India to Russia. Premium bulk supply and customized private label solutions for Russian distributors.",
    url: "https://www.indianfoodtech.com/peanut-butter-supplier-russia",
    siteName: "Indian Foodtech",
    type: "website",
    locale: "en_RU",
  },
  alternates: {
    canonical: "https://www.indianfoodtech.com/peanut-butter-supplier-russia",
    languages: {
      "en-RU": "https://www.indianfoodtech.com/peanut-butter-supplier-russia",
      "x-default": "https://www.indianfoodtech.com/",
    },
  },
};

export default function Page() {
  return (
    <>
      <MarketSchema
        country="Russia"
        type="Supplier"
        description="Reliable peanut butter supplier in Russia. Indian Foodtech offers premium bulk supply and private label solutions for the Russian market."
        url="https://www.indianfoodtech.com/peanut-butter-supplier-russia"
      />
      <PeanutButterSupplierRussia />
    </>
  );
}
