import { Metadata } from "next";
import PeanutButterSupplierPortugal from "./PeanutButterSupplierPortugal";
import MarketSchema from "@/components/MarketSchema";

export const metadata: Metadata = {
  title: "Peanut Butter Supplier Portugal | Bulk Supply India",
  description:
    "Reliable peanut butter supplier in Portugal. Indian Foodtech offers premium bulk supply, private label, and industrial solutions for the Portuguese market.",
  keywords: [
    "peanut butter supplier portugal",
    "bulk peanut butter portugal",
    "private label peanut butter portugal",
    "fornecedor de manteiga de amendoim",
    "manteiga de amendoim por atacado",
    "importação de manteiga de amendoim portugal",
    "peanut butter supplier lisbon",
    "portuguese food importers",
    "european peanut butter supply",
    "peanut butter import Portugal",
    "Portugal peanut butter supplier",
    "peanut butter manufacturer Portugal",
    "private label peanut butter Portugal",
    "bulk peanut butter Portugal",
    "wholesale peanut butter Portugal",
    "import peanut butter Portugal",
    "peanut butter exporter Portugal",
    "natural peanut butter Portugal",
    "organic peanut butter Portugal",
    "creamy peanut butter Portugal",
    "crunchy peanut butter Portugal",
    "high protein peanut butter Portugal",
    "premium peanut butter Portugal",
    "peanut butter distributor Portugal",
    "AGRION peanut butter",
    "food importer Portugal",
    "food distributor Portugal",
    "private label food manufacturer Portugal",
    "manteiga de amendoim Portugal",
    "fornecedor de manteiga de amendoim Portugal",
    "fabricante de manteiga de amendoim Portugal",
    "manteiga de amendoim por atacado",
    "manteiga de amendoim a granel",
    "importação de manteiga de amendoim",
    "exportação de manteiga de amendoim",
    "manteiga de amendoim natural",
    "manteiga de amendoim biológica",
    "manteiga de amendoim cremosa",
    "manteiga de amendoim crocante",
    "manteiga de amendoim rica em proteínas",
    "manteiga de amendoim marca própria",
    "private label manteiga de amendoim",
    "produção por contrato",
    "importador de alimentos Portugal",
    "distribuidor de alimentos Portugal",
    "fornecedor de alimentos Portugal",
    "buy peanut butter in bulk Portugal",
    "wholesale peanut butter supplier Portugal",
    "private label peanut butter manufacturer Portugal",
    "natural peanut butter distributor Portugal",
    "organic peanut butter supplier Portugal",
    "high protein peanut butter Portugal",
    "peanut butter for supermarkets Portugal",
    "food importer Portugal",
    "bulk peanut butter exporter to Portugal",
    "premium peanut butter supplier Portugal",
    "manteiga de amendoim por atacado Portugal",
    "fornecedor de manteiga de amendoim para supermercados",
    "fabricante de manteiga de amendoim marca própria",
    "importador de manteiga de amendoim Portugal",
    "distribuidor de manteiga de amendoim Portugal",
    "manteiga de amendoim biológica Portugal",
    "Peanut butter supplier Lisbon",
    "wholesale peanut butter Portugal",
    "private label peanut butter Portugal",
    "manteiga de amendoim Lisboa",
    "fornecedor de manteiga de amendoim Portugal",
    "manteiga de amendoim por atacado Portugal",
    "importador de manteiga de amendoim Porto",
    "OEM peanut butter Portugal",
    "ODM peanut butter supplier Portugal",
    "private label nut butter manufacturer Portugal",
    "bulk peanut butter for retailers",
    "healthy food distributor Portugal",
    "OEM manteiga de amendoim",
    "ODM manteiga de amendoim",
    "produção de manteiga de amendoim marca própria",
    "fornecedor de alimentos saudáveis Portugal",
    "organic peanut butter Portugal",
    "vegan peanut butter Portugal",
    "protein peanut butter Portugal",
    "sugar free peanut butter Portugal",
    "natural peanut butter Portugal",
    "manteiga de amendoim biológica",
    "manteiga de amendoim vegan",
    "manteiga de amendoim rica em proteínas",
    "manteiga de amendoim sem açúcar",
    "manteiga de amendoim natural",
    "sports nutrition peanut butter Portugal",
    "fitness peanut butter Portugal",
    "healthy snack supplier Portugal",
    "gym nutrition peanut butter Portugal",
    "high protein spread Portugal",
    "nutrição desportiva manteiga de amendoim",
    "manteiga de amendoim fitness",
    "snacks saudáveis Portugal",
    "creme proteico de amendoim",
    "private label peanut butter manufacturer Portugal",
    "contract manufacturing peanut butter Portugal",
    "white label peanut butter Portugal",
    "OEM food manufacturer Portugal",
    "custom peanut butter manufacturer Portugal",
    "Portugal peanut butter market",
    "Portugal nut butter market",
  ],
  openGraph: {
    title: "Peanut Butter Supplier Portugal | Indian Foodtech",
    description:
      "High-quality peanut butter exported from India to Portugal. Premium bulk supply and customized private label solutions for Portuguese distributors.",
    url: "https://www.indianfoodtech.com/peanut-butter-supplier-portugal",
    siteName: "Indian Foodtech",
    type: "website",
    locale: "en_PT",
  },
  alternates: {
    canonical: "https://www.indianfoodtech.com/peanut-butter-supplier-portugal",
    languages: {
      "en-PT": "https://www.indianfoodtech.com/peanut-butter-supplier-portugal",
      "x-default": "https://www.indianfoodtech.com/",
    },
  },
};

export default function Page() {
  return (
    <>
      <MarketSchema
        country="Portugal"
        type="Supplier"
        description="Reliable peanut butter supplier in Portugal. Indian Foodtech offers premium bulk supply and private label solutions for the Portuguese market."
        url="https://www.indianfoodtech.com/peanut-butter-supplier-portugal"
      />
      <PeanutButterSupplierPortugal />
    </>
  );
}
