import { Metadata } from "next";
import PeanutButterImportSwitzerland from "./PeanutButterImportSwitzerland";
import MarketSchema from "@/components/MarketSchema";

export const metadata: Metadata = {
  title: "Peanut Butter Importer Switzerland | Indian Foodtech",
  description:
    "Reliable peanut butter importer in Switzerland. Indian Foodtech offers premium bulk supply, private label, and industrial solutions for the Swiss market.",
  keywords: [
    "peanut butter importer switzerland",
    "bulk peanut butter switzerland",
    "private label peanut butter switzerland",
    "erdnussbutter importeur",
    "erdnussbutter großhandel",
    "erdnussbutter import schweiz",
    "peanut butter supplier zurich",
    "swiss food importers",
    "european peanut butter supply",
    "peanut butter import Switzerland",
    "Switzerland peanut butter supplier",
    "peanut butter manufacturer Switzerland",
    "private label peanut butter Switzerland",
    "bulk peanut butter Switzerland",
    "wholesale peanut butter Switzerland",
    "import peanut butter Switzerland",
    "peanut butter exporter Switzerland",
    "natural peanut butter Switzerland",
    "organic peanut butter Switzerland",
    "creamy peanut butter Switzerland",
    "crunchy peanut butter Switzerland",
    "high protein peanut butter Switzerland",
    "premium peanut butter Switzerland",
    "peanut butter distributor Switzerland",
    "AGRION peanut butter",
    "food importer Switzerland",
    "food distributor Switzerland",
    "private label food manufacturer Switzerland",
    "Erdnussbutter Schweiz",
    "Erdnussbutter Lieferant Schweiz",
    "Erdnussbutter Hersteller Schweiz",
    "Erdnussbutter Großhandel",
    "Bio Erdnussbutter",
    "natürliche Erdnussbutter",
    "cremige Erdnussbutter",
    "knusprige Erdnussbutter",
    "proteinreiche Erdnussbutter",
    "Private Label Erdnussbutter",
    "Lebensmittelimporteur Schweiz",
    "Lebensmittellieferant Schweiz",
    "beurre de cacahuète Suisse",
    "fournisseur de beurre de cacahuète Suisse",
    "fabricant de beurre de cacahuète Suisse",
    "beurre de cacahuète en gros",
    "beurre de cacahuète biologique",
    "beurre de cacahuète naturel",
    "beurre de cacahuète crémeux",
    "beurre de cacahuète croquant",
    "beurre de cacahuète riche en protéines",
    "marque privée beurre de cacahuète",
    "importateur alimentaire Suisse",
    "buy peanut butter in bulk Switzerland",
    "wholesale peanut butter supplier Switzerland",
    "private label peanut butter manufacturer Switzerland",
    "natural peanut butter distributor Switzerland",
    "organic peanut butter supplier Switzerland",
    "high protein peanut butter Switzerland",
    "food importer Switzerland",
    "bulk peanut butter exporter to Switzerland",
    "premium peanut butter supplier Switzerland",
    "Erdnussbutter Großhandel Schweiz",
    "Private Label Erdnussbutter Hersteller",
    "Erdnussbutter Importeur Schweiz",
    "beurre de cacahuète en gros Suisse",
    "fabricant de beurre de cacahuète marque privée",
    "importateur de beurre de cacahuète Suisse",
    "peanut butter supplier Zurich",
    "wholesale peanut butter Switzerland",
    "private label peanut butter Switzerland",
    "Erdnussbutter Zürich",
    "Erdnussbutter Lieferant Schweiz",
    "Erdnussbutter Großhandel Schweiz",
    "beurre de cacahuète Genève",
    "fournisseur de beurre de cacahuète Suisse",
    "OEM peanut butter Switzerland",
    "ODM peanut butter supplier Switzerland",
    "private label nut butter manufacturer Switzerland",
    "bulk peanut butter for retailers",
    "healthy food distributor Switzerland",
    "OEM Erdnussbutter",
    "ODM Erdnussbutter",
    "Private Label Erdnussbutter Produktion",
    "OEM beurre de cacahuète",
    "ODM beurre de cacahuète",
    "fabrication sous marque privée",
    "organic peanut butter Switzerland",
    "vegan peanut butter Switzerland",
    "protein peanut butter Switzerland",
    "sugar free peanut butter Switzerland",
    "clean label peanut butter Switzerland",
    "Bio Erdnussbutter",
    "vegane Erdnussbutter",
    "Protein Erdnussbutter",
    "zuckerfreie Erdnussbutter",
    "beurre de cacahuète biologique",
    "beurre de cacahuète vegan",
    "beurre de cacahuète sans sucre",
  ],
  openGraph: {
    title: "Peanut Butter Importer Switzerland | Indian Foodtech",
    description:
      "High-quality peanut butter exported from India to Switzerland. Premium bulk supply and customized private label solutions for Swiss distributors.",
    url: "https://www.indianfoodtech.com/peanut-butter-import-switzerland",
    siteName: "Indian Foodtech",
    type: "website",
    locale: "en_CH",
  },
  alternates: {
    canonical: "https://www.indianfoodtech.com/peanut-butter-import-switzerland",
    languages: {
      "en-CH": "https://www.indianfoodtech.com/peanut-butter-import-switzerland",
      "x-default": "https://www.indianfoodtech.com/",
    },
  },
};

export default function Page() {
  return (
    <>
      <MarketSchema
        country="Switzerland"
        type="Importer"
        description="Reliable peanut butter importer in Switzerland. Indian Foodtech offers premium bulk supply, private label, and industrial solutions for the Swiss market."
        url="https://www.indianfoodtech.com/peanut-butter-import-switzerland"
      />
      <PeanutButterImportSwitzerland />
    </>
  );
}
