import { Metadata } from "next";
import PeanutButterExportToVietnam from "./PeanutButterExportToVietnam";
import MarketSchema from "@/components/MarketSchema";

export const metadata: Metadata = {
  title: "Peanut Butter Exporter to Vietnam | Nhà xuất khẩu bơ đậu phộng",
  description:
    "Reliable peanut butter exporter to Vietnam. Indian Foodtech offers premium bulk supply, private label, and industrial solutions for the Vietnamese market.",
  keywords: [
    "peanut butter exporter to vietnam",
    "nhà xuất khẩu bơ đậu phộng Việt Nam",
    "bulk peanut butter ho chi minh city",
    "private label peanut butter vietnam",
    "peanut butter supplier hanoi",
    "vietnamese food exporters to",
    "peanut butter export to Vietnam",
    "Vietnam peanut butter supplier",
    "peanut butter manufacturer Vietnam",
    "private label peanut butter Vietnam",
    "bulk peanut butter Vietnam",
    "wholesale peanut butter Vietnam",
    "export peanut butter to Vietnam",
    "peanut butter exporter Vietnam",
    "natural peanut butter Vietnam",
    "organic peanut butter Vietnam",
    "creamy peanut butter Vietnam",
    "crunchy peanut butter Vietnam",
    "high protein peanut butter Vietnam",
    "premium peanut butter Vietnam",
    "peanut butter distributor Vietnam",
    "AGRION peanut butter",
    "food exporter to Vietnam",
    "food distributor Vietnam",
    "private label food manufacturer Vietnam",
    "bơ đậu phộng Việt Nam",
    "nhà cung cấp bơ đậu phộng Việt Nam",
    "nhà sản xuất bơ đậu phộng Việt Nam",
    "bơ đậu phộng bán sỉ",
    "bơ đậu phộng số lượng lớn",
    "xuất khẩu bơ đậu phộng",
    "xuất khẩu bơ đậu phộng",
    "bơ đậu phộng tự nhiên",
    "bơ đậu phộng hữu cơ",
    "bơ đậu phộng mịn",
    "bơ đậu phộng giòn",
    "bơ đậu phộng giàu protein",
    "bơ đậu phộng nhãn riêng",
    "private label bơ đậu phộng",
    "gia công bơ đậu phộng",
    "nhà xuất khẩu thực phẩm Việt Nam",
    "nhà phân phối thực phẩm Việt Nam",
    "nhà cung cấp thực phẩm Việt Nam",
    "buy peanut butter in bulk Vietnam",
    "wholesale peanut butter supplier Vietnam",
    "private label peanut butter manufacturer Vietnam",
    "natural peanut butter distributor Vietnam",
    "organic peanut butter supplier Vietnam",
    "high protein peanut butter Vietnam",
    "peanut butter for supermarkets Vietnam",
    "food exporter to Vietnam",
    "bulk peanut butter exporter to Vietnam",
    "premium peanut butter supplier Vietnam",
    "bơ đậu phộng bán sỉ Việt Nam",
    "nhà xuất khẩu bơ đậu phộng Việt Nam",
    "nhà sản xuất bơ đậu phộng nhãn riêng",
    "gia công bơ đậu phộng OEM",
    "gia công bơ đậu phộng ODM",
    "bơ đậu phộng hữu cơ Việt Nam",
    "Peanut butter supplier Ho Chi Minh City",
    "wholesale peanut butter Vietnam",
    "private label peanut butter Vietnam",
    "bơ đậu phộng TP Hồ Chí Minh",
    "nhà cung cấp bơ đậu phộng Việt Nam",
    "bơ đậu phộng bán sỉ Việt Nam",
    "nhà xuất khẩu bơ đậu phộng Hà Nội",
    "OEM peanut butter Vietnam",
    "ODM peanut butter supplier Vietnam",
    "private label nut butter manufacturer Vietnam",
    "bulk peanut butter for retailers",
    "healthy food distributor Vietnam",
    "OEM bơ đậu phộng",
    "ODM bơ đậu phộng",
    "bơ đậu phộng nhãn riêng",
    "nhà cung cấp thực phẩm sức khỏe Việt Nam",
    "protein peanut butter Vietnam",
    "organic peanut butter Vietnam",
    "sugar free peanut butter Vietnam",
    "vegan peanut butter Vietnam",
    "healthy peanut butter Vietnam",
    "bơ đậu phộng giàu protein",
    "bơ đậu phộng hữu cơ",
    "bơ đậu phộng không đường",
    "bơ đậu phộng thuần chay",
    "bơ đậu phộng tốt cho sức khỏe",
    "exported to peanut butter Vietnam",
    "premium peanut butter Vietnam",
    "fitness nutrition products Vietnam",
    "healthy snack supplier Vietnam",
    "supermarket peanut butter supplier Vietnam",
    "bơ đậu phộng xuất khẩu",
    "bơ đậu phộng cao cấp",
    "thực phẩm dinh dưỡng thể thao",
    "thực phẩm ăn kiêng",
    "Vietnam peanut butter market",
    "Vietnam nut butter market",
  ],
  openGraph: {
    title: "Peanut Butter Exporter to Vietnam | Indian Foodtech",
    description:
      "High-quality peanut butter exported from India to Vietnam. Premium bulk supply and customized private label solutions for Southeast Asian distributors.",
    url: "https://www.indianfoodtech.com/peanut-butter-export-to-vietnam",
    siteName: "Indian Foodtech",
    type: "website",
    locale: "vi_VN",
  },
  alternates: {
    canonical: "https://www.indianfoodtech.com/peanut-butter-export-to-vietnam",
    languages: {
      "vi-VN": "https://www.indianfoodtech.com/peanut-butter-export-to-vietnam",
      "x-default": "https://www.indianfoodtech.com/",
    },
  },
};

export default function Page() {
  return (
    <>
      <MarketSchema
        country="Vietnam"
        type="Exporter"
        description="Reliable peanut butter exporter to Vietnam. Indian Foodtech offers premium bulk supply, private label, and industrial solutions for the Vietnamese market."
        url="https://www.indianfoodtech.com/peanut-butter-export-to-vietnam"
      />
      <PeanutButterExportToVietnam />
    </>
  );
}
